rerun-triggers: ['mtime']
notemp: true
printshellcmds: false
keep-going: true
resources: ['network_connections=3', 'mem_mb=500000']
use-conda: true
conda-frontend: 'mamba'
conda-prefix: '/pollard/home/bsmith/.snakemake/conda'
config:
  - 'USE_CUDA=0'
  - 'MAX_THREADS=24'
  - 'jupyter_port=8818'
  - 'server_port=8819'
